apiVersion : apps/v1
kind : Deployment
metadata:
  name   : {{ .Release.Name }}-deployment
  labels :
    app : {{ .Release.Name }}-k8s-deployment
spec:
  replicas : {{ .Values.replicaCount }}
  strategy :
    type : RollingUpdate
    rollingUpdate :
      maxSurge : {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable : {{ .Values.rollingUpdate.maxUnavailable }}
  selector :
    matchLabels :
      project : {{ .Release.Name }}-web-3
  template :
    metadata :
      labels :
        project : {{ .Release.Name }}-web-3
    spec :
      containers :
        - name  : {{ .Release.Name }}-page-1
          image : {{ .Values.container.image }}
          ports :
            - containerPort : 80
          readinessProbe :
            httpGet :
              path : /
              port : 80
            initialDelaySeconds : {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds : {{ .Values.readinessProbe.periodSeconds }}
            successThreshold : {{ .Values.readinessProbe.successThreshold }}
          livenessProbe :
            httpGet :
              path : /
              port : 80
            initialDelaySeconds : {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds : {{ .Values.livenessProbe.periodSeconds }}
            successThreshold : {{ .Values.livenessProbe.successThreshold }}
