apiVersion : v1
kind : Service
metadata :
  name   : {{ .Release.Name }}-byndyusoft-service
  labels :
    env   : prod
    owner : Viktor
spec :
  type : LoadBalancer
  selector :
      project : {{ .Release.Name }}-web-3   # Select PODs
  ports :
    - name       : {{ .Release.Name }}-listener
      protocol   : TCP
      port       : 80   # Port on LoadBalancer
      targetPort : 80   # Port on POD
